export const PIPELINE_CANVAS_ROUTES_ROW_HEIGHT = 44;
export const PIPELINE_CANVAS_ROUTES_ISLAND_HEIGHT = 30;
export const PIPELINE_CANVAS_ROUTES_SOURCE_ISLAND_WIDTH = 300;
export const PIPELINE_CANVAS_ROUTES_SINK_ISLAND_WIDTH = 200;

export const PIPELINE_CANVAS_ROUTES_LIST_PADDING_X = 12;
export const PIPELINE_CANVAS_ROUTES_LIST_PADDING_Y = 9;
export const PIPELINE_CANVAS_ROUTES_OVERSCAN = 6;

export const PIPELINE_CANVAS_ROUTES_EDGE_CONTROL_INSET = 24;
export const PIPELINE_CANVAS_ROUTES_EDGE_CONTROL_GAP = 6;
export const PIPELINE_CANVAS_ROUTES_EDGE_MIN_WIDTH = 560;
export const PIPELINE_CANVAS_ROUTES_EDGE_FAN_CONTROL_X = 14;
export const PIPELINE_CANVAS_ROUTES_EDGE_FAN_END_X = 28;
export const PIPELINE_CANVAS_ROUTES_EDGE_DASH_ARRAY = "5 5";
export const PIPELINE_CANVAS_ROUTES_EDGE_DASH_PERIOD = 10;
export const PIPELINE_CANVAS_ROUTES_EDGE_DASH_DURATION = "0.5s";

export const PIPELINE_CANVAS_ROUTES_SEARCH_WIDTH = 280;
export const PIPELINE_CANVAS_ROUTES_SINK_FILTER_WIDTH = 220;
export const PIPELINE_CANVAS_ROUTES_SINKS_PINNED_OPTION_ID = "all";

export const PIPELINE_CANVAS_ROUTES_READ_MODE_SELECT_WIDTH = 112;
export const PIPELINE_CANVAS_ROUTES_CURSOR_SELECT_WIDTH = 136;
export const PIPELINE_CANVAS_ROUTES_WRITE_MODE_SELECT_WIDTH = 104;
